/**
 * @file  AbstractProtocolHandler.java
 * @brief Generated by the OrbJavaClientGenerator 2.4.1
 * @date  Sat Dec 22 20:24:26 JST 2012
 *
 * Copyright 2012 Sony Corporation
 */
package com.sony.mexi.orb.client.serviceguide.v1_0;

import com.sony.mexi.webapi.DefaultCallbacks;

public abstract class AbstractProtocolHandler
    extends DefaultCallbacks
    implements com.sony.mexi.webapi.ProtocolHandler {
}
