/**
 * Skeleton is generated by the OrbJavaClientGenerator 2.4.1 at Sat Dec 22 20:24:26 JST 2012
 *
 * Copyright 2012 Sony Corporation
 */
package com.sony.mexi.orb.client.serviceguide.v1_0;

public class ProtocolHandlerImpl extends AbstractProtocolHandler {

    @Override
    public void handleProtocols(java.lang.String p0,
                java.lang.String[] p1) {
        // TODO: not implemented.
    }

}
