/**
 * @file  AbstractGetSupportedWhiteBalanceCallback.java
 * @brief Generated by the OrbJavaClientGenerator 2.4.1
 * @date  Sat Dec 22 14:53:20 JST 2012
 *
 * Copyright 2012 Sony Corporation
 */
package com.sony.mexi.orb.client.smartremotecontroltestclient.v1_2;

import com.sony.mexi.webapi.DefaultCallbacks;

public abstract class AbstractGetSupportedWhiteBalanceCallback
    extends DefaultCallbacks
    implements com.sony.scalar.webapi.service.camera.v1_2.whitebalance.GetSupportedWhiteBalanceCallback {
}
