/**
 * Skeleton is generated by the OrbJavaClientGenerator 2.4.1 at Sat Dec 22 14:53:20 JST 2012
 *
 * Copyright 2012 Sony Corporation
 */
package com.sony.mexi.orb.client.smartremotecontroltestclient.v1_2;

public class GetAvailableCreativeStyleCallbackImpl extends AbstractGetAvailableCreativeStyleCallback {

    @Override
    public void returnCb(com.sony.scalar.webapi.service.camera.v1_2.common.struct.CreativeStyleParams p0,
                com.sony.scalar.webapi.service.camera.v1_2.common.struct.CreativeStyleParamCandidate[] p1) {
        // TODO: not implemented.
    }

}
