/**
 * Skeleton is generated by the OrbJavaClientGenerator 2.4.1 at Sat Dec 22 14:53:20 JST 2012
 *
 * Copyright 2012 Sony Corporation
 */
package com.sony.mexi.orb.client.smartremotecontroltestclient.v1_2;

public class GetSelfTimerCallbackImpl extends AbstractGetSelfTimerCallback {

    @Override
    public void returnCb(int p0) {
        // TODO: not implemented.
    }

}
