/**
 * Skeleton is generated by the OrbJavaClientGenerator 2.4.1 at Sat Dec 22 14:53:20 JST 2012
 *
 * Copyright 2012 Sony Corporation
 */
package com.sony.mexi.orb.client.smartremotecontroltestclient.v1_2;

public class GetTouchAFPositionCallbackImpl extends AbstractGetTouchAFPositionCallback {

    @Override
    public void returnCb(boolean p0,
                double[] p1) {
        // TODO: not implemented.
    }

}
