/**
 * Skeleton is generated by the OrbJavaClientGenerator 2.4.1 at Sat Dec 22 14:53:20 JST 2012
 *
 * Copyright 2012 Sony Corporation
 */
package com.sony.mexi.orb.client.smartremotecontroltestclient.v1_2;

public class SetTouchAFPositionCallbackImpl extends AbstractSetTouchAFPositionCallback {

    @Override
    public void returnCb(boolean p0,
                java.lang.String p1,
                double[] p2,
                double[] p3,
                double[] p4) {
        // TODO: not implemented.
    }

}
